# Generated by Django 4.1 on 2022-11-17 01:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='EX: Suco, Lanche, ...', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descricao', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descrição')),
                ('dataAdicao', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('vendendo', models.BooleanField(default=True)),
                ('imagem', models.ImageField(null=True, upload_to='images/produtos')),
                ('tipoProduto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.tipoproduto', verbose_name='Tipo do Produto')),
            ],
        ),
    ]
