# Generated by Django 4.1 on 2022-11-17 01:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mesas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moduloEmail', '0001_initial'),
        ('equipe', '0001_initial'),
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorTotal', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('valorPago', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('atualizada', models.DateTimeField(auto_now=True)),
                ('dataHoraCriada', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('dataCriada', models.DateField(auto_now_add=True)),
                ('encerrada', models.BooleanField(default=False)),
                ('dataHoraEncerrada', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('contaAnon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='moduloEmail.emailanonimo')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipe.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número da Mesa:')),
                ('ocupada', models.BooleanField(blank=True, default=False)),
                ('garcom', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comanda_Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('quantidadeEntregue', models.IntegerField(default=0)),
                ('horaPedido', models.DateTimeField(default=django.utils.timezone.now)),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesas.comanda')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.produto')),
            ],
        ),
        migrations.AddField(
            model_name='comanda',
            name='nmrMesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mesas.mesa', validators=[mesas.models.Comanda.validate_nmrMesa]),
        ),
        migrations.AddField(
            model_name='comanda',
            name='produtos',
            field=models.ManyToManyField(through='mesas.Comanda_Produto', to='estoque.produto'),
        ),
    ]
